addons:
  - nekox@mini # ( full | fullAppleEmoji | mini | miniAppleEmoji )
  - instander
  - mixplorer@silver # Silver includes addons

custom:
  - app: xManager (Spotify)
    source: github
    args:
      - xManager-v2/xManager-Spotify
      - xManager.apk

  - app: Infinity for Reddit
    package: ml.docilealligator.infinityforreddit
    source: fdroid

  - app: VLC
    package: org.videolan.vlc
    source: playstore

  # - app: AdAway
  #   package: org.adaway
  #   source: fdroid

  # - app: Vanced Manager
  #   source: github
  #   args:
  #     - YTVanced/VancedManager
  #     - manager.apk

  - app: Whatsapp
    package: com.whatsapp
    source: playstore

  # - app: Google Keep - notes and lists
  #   package: com.google.android.keep
  #   source: playstore

  - app: Google Maps
    package: com.google.android.apps.maps
    source: playstore

  # - app: Google Calendar
  #   package: com.google.android.calendar
  #   source: playstore

  - app: Adobe Scan
    package: com.adobe.scan.android
    source: playstore

  # - app: Gboard
  #   package: com.google.android.inputmethod.latin
  #   source: playstore

  - app: Microsoft Office
    package: com.microsoft.office.officehubrow
    source: playstore

  - app: Google Photos
    package: com.google.android.apps.photos
    source: playstore

  - app: Termux
    package: com.termux
    source: fdroid

  - app: Mi Remote controller
    package: com.duokan.phone.remotecontroller
    source: playstore

  - app: Microsoft Teams
    package: com.microsoft.teams
    source: playstore

  # - app: Google Camera
  #   args:
  #     - best
  #   source: gcam

  - app: Bromite
    source: github
    args:
      - bromite/bromite
      - arm64_ChromePublic.apk

  - app: LinkedIn
    package: com.linkedin.android
    source: playstore
